// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5lhB3rbNIj2m5EZ2GJlTA0zzZfxiLL5w',
    appId: '1:141477545510:web:0afb15d50dfa5bf036c8e7',
    messagingSenderId: '141477545510',
    projectId: 'cityfix-c5565',
    authDomain: 'cityfix-c5565.firebaseapp.com',
    storageBucket: 'cityfix-c5565.firebasestorage.app',
    measurementId: 'G-TSTDLH2GCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZUyuZrm3DoXqRALgwJrzei7JffqUCZYA',
    appId: '1:141477545510:android:dd120f7dcd1a583f36c8e7',
    messagingSenderId: '141477545510',
    projectId: 'cityfix-c5565',
    storageBucket: 'cityfix-c5565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqz5uC8um-01RcVQhOI--JFlpdLYC4AE',
    appId: '1:141477545510:ios:6643c6b8e276017f36c8e7',
    messagingSenderId: '141477545510',
    projectId: 'cityfix-c5565',
    storageBucket: 'cityfix-c5565.firebasestorage.app',
    androidClientId: '141477545510-7i83i9cvs07agh6fsnlhlhppfs856ift.apps.googleusercontent.com',
    iosClientId: '141477545510-94ej73ofeql5oe1a2nouqp6m6v6dn86g.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqz5uC8um-01RcVQhOI--JFlpdLYC4AE',
    appId: '1:141477545510:ios:6643c6b8e276017f36c8e7',
    messagingSenderId: '141477545510',
    projectId: 'cityfix-c5565',
    storageBucket: 'cityfix-c5565.firebasestorage.app',
    androidClientId: '141477545510-7i83i9cvs07agh6fsnlhlhppfs856ift.apps.googleusercontent.com',
    iosClientId: '141477545510-94ej73ofeql5oe1a2nouqp6m6v6dn86g.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5lhB3rbNIj2m5EZ2GJlTA0zzZfxiLL5w',
    appId: '1:141477545510:web:e676fbaf5be85ae736c8e7',
    messagingSenderId: '141477545510',
    projectId: 'cityfix-c5565',
    authDomain: 'cityfix-c5565.firebaseapp.com',
    storageBucket: 'cityfix-c5565.firebasestorage.app',
    measurementId: 'G-DKSSW8J5JN',
  );
}
